eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8989
spring:
  application:
    name: zipkin-client0
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411